# Predicting with regression, multiple covariates

Example: predicting wages
book. Introduction to Statistical Learning
```{r}
library(ISLR)
library(ggplot2)
library(caret)
data(Wage)
Wage <- subset(Wage, select = -c(logwage)) #logwage output
summary(Wage)
```

```{r}
inTrain <- createDataPartition(y = Wage$wage, p = 0.7, list = FALSE)
training <- Wage[inTrain,]
testing <- Wage[-inTrain,]
dim(training)
dim(testing)
```
## Feature plot

```{r}
featurePlot(x = training[, c("age", "education", "jobclass")],
            y = training$wage, 
            plot = "pairs")

qplot(age, wage, data = training)
qplot(age, wage, colour = jobclass, data = training)
qplot(age, wage, colour = education, data = training)
```

## Fit a linear model

```{r}
modFit <- train(wage ~ age + jobclass + education,
                method = "lm",
                data = training)
finMod <- modFit$finalModel
print(finMod)
```


## Diagnostics

```{r}
plot(finMod, 1, pch = 19, cex = 0.5, col = "#00000010")

qplot(finMod$fitted.values, finMod$residuals, colour = race, data = training)

# Plot by index
plot(finMod$residuals, pch = 19)

# Predicted versus truth in test set
pred <- predict(modFit, testing)
qplot(wage, pred, colour = year, data = testing)

# If you want to use all covariaes

mofFitAll <- train(wage ~., data = training, method = "lm")
pred <- predict(modFitAl, testing)
qplot(wage, pred, data = testing)
```
